directory:Torrents/
login_token:
base_url:http://audiobookbay.nl
avoid_duplicates:True
user_agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
categories:litrpg
tags:
search_terms:
search_extras:
auto_run:True
wait_time:3600
torrent_list:list.txt
silent:False